const CONSTANTS = {
  APP_TITLE: 'Blog App',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  ENTER_AN_EMAIL: 'Enter an Email Address',
  ENTER_PASSWORD: 'Enter your Password',
  LOGIN: 'Login',
  LOGOUT: 'Logout',
  CREATE_AN_ACCOUNT: 'Create An Account',
  NAME: 'Name',
  CONFIRM_PASSWORD: 'Confirm Password',
  RE_ENTER_YOUR_PASSWORD: 'Re-enter Your Password',
  ENTER_YOUR_NAME: 'Enter Your Full Name',
  REGISTER: 'Register',
  ALREADY_EXISTS: 'Already have an account? Login',
  API_ERROR: 'API is not working properly',
  POSTS: 'Posts',
  COMMENTS: 'Comments',
  CREATE_NEW_POST: 'Create New Post',
  CLOSE_THE_DIALOG: 'Dismiss',
  NEW_POST: 'New Post',
  TITLE: 'Title',
  BODY: 'Body',
  PUBLISH_THE_POST: 'Publish',
  EDIT: 'Edit',
  DELETE: 'Delete',
  EDIT_DONE: 'Done',
  GO_BACK: 'Back to posts',
  POST: 'Post',
  LOADING: 'Loading...',
  PUBLISH_THE_COMMENT: 'Publish Comment',
  ADD_NEW_COMMENT: 'Add New Comment',
  POST_TITLE: 'Title: ',
  POST_BODY: 'Body: ',
  SOMETHING_WENT_WRONG: 'Something went wrong.',
  MY_PROFILE: 'My Profile',
  LOGIN_FIRST: 'Login first to check comments',
  DISLIKED: 'Disliked',
  DISLIKE: 'Dislike',
  LIKED: 'Liked',
  LIKE: 'Like',
  UNLIKE: 'Unlike',
  LIKES: 'Like(s)',
  EMAIL_FIELD: 'email',
  PASSWORD_FIELD: 'password',
  NAME_FIELD: 'name',
  CONFIRM_PASSWORD_FIELD: 'confirmPassword',
  POSTED: 'Posted',
  EDITED: 'Edited',
  USER_ADDED: 'User Added',
  LOGGED_IN: 'Logged In',
  COMMENTED: 'Commented',
  UPDATED: 'Updated',
  PUBLISHED: 'published',
  NOT_PUBLISHED: 'not_published',
  SAVE: 'Save Post',
  PUBLISH_NOW: 'Publish Now',
  HIDE_PUBLISH: 'Hide this',
  PUBLISHED_SUCCESSFULLY: 'Published Succesfully',
  UNPUBLISHED_SUCCESSFULLY: 'Unpublished Successfully',
  UNPUBLISH_NOW: 'Unpublish Now',
  INCORRECT_EMAIL_OR_PASSWORD: 'Invalid Email or Password',
  USER_ALREADY_EXISTS: 'User already exists',
  ADD_ALL_FIELDS: 'Please add all fields',
  INVALID_USER_DATA: 'Invalid user data',
  ENTER_NAME: 'Please add a name',
  ENTER_EMAIL: 'Please enter email',
  NOT_AUTH_NO_TOKEN: 'Not authorized, no token',
  NOT_AUTHORIZED: 'Not Authorized',
  MINUS_PASSWORD: '-password',
  BEARER: 'Bearer',
  ENTER_TITLE: 'Please add title',
  ENTER_BODY: 'Please add body',
  ENTER_COMMENT: 'Please add comment',
  COMMENTS_SCHEMA: 'comments',
  POSTS_SCHEMA: 'posts',
  USERS_SCHEMA: 'users',
  CANT_GET_INDIVIDUAL_POST: 'Cant get single post',
  EDIT_FAILED: 'Edit Failed',
  DELETION_FAILED: 'Deletion Failed',
  PUBLISH_NEW_POST_FAILED: 'Cant publish new post',
  PUBLISH_NEW_COMMENT_FAILED: 'Cant publish new comment',
  LOGIN_FAILED: 'Login failed',
  SIGNUP_FAILED: 'Signup failed',
  PROFILE_DATA_FAILED: 'Profile data loading failed',
  POST_FETCH_FAILED: 'Cant fetch all posts',
  COMMENTS_FETCH_FAILED: 'Cant fetch all comments',
  LIKE_DISLIKE_FAILED: 'Cant like or disliked',
  PUBLISHED_FAILED: 'Published Failied',
  UNPUBLISHED_FAILED: 'Unpublished Failed',
  GENERATE_TOKEN_FAILED: 'Generate Token Failed',
  LOGOUT_FAILED: 'Logout Failed',
  NEW_POST_FAILED: 'New Post Failed',
  DISLIKE_FAILED: 'Dislike Failed',
  LIKE_FAILED: 'Like Failed'
}

export default CONSTANTS
