const CONSTANTS = {
    APP_TITLE: 'Blog App',
    EMAIL: 'Email',
    PASSWORD: 'Password',
    ENTER_AN_EMAIL: 'Enter an Email Address',
    ENTER_PASSWORD: 'Enter your Password',
    LOGIN: 'Login',
    LOGOUT: 'Logout',
    CREATE_AN_ACCOUNT: 'Create An Account',
    NAME: 'Name',
    CONFIRM_PASSWORD: 'Confirm Password',
    RE_ENTER_YOUR_PASSWORD: 'Re-enter Your Password',
    ENTER_YOUR_NAME: "Enter Your Full Name",
    REGISTER: "Register",
    ALREADY_EXISTS: 'Already have an account? Login',
    API_ERROR: 'API is not working properly',
    POSTS: 'Posts',
    COMMENTS: 'Comments',
    CREATE_NEW_POST: 'Create New Post',
    CLOSE_THE_DIALOG: 'Dismiss',
    NEW_POST: 'New Post',
    TITLE: 'Title',
    BODY: 'Body',
    PUBLISH_THE_POST: 'Publish',
    EDIT: 'Edit',
    DELETE: 'Delete',
    EDIT_DONE: 'Done',
    GO_BACK: 'Back to posts',
    POST: 'Post',
    LOADING: 'Loading...',
    PUBLISH_THE_COMMENT: 'Publish Comment',
    ADD_NEW_COMMENT: 'Add New Comment',
    POST_TITLE: 'Title: ',
    POST_BODY: 'Body: ',
    SOMETHING_WENT_WRONG: 'Something went wrong.',
    MY_PROFILE: 'My Profile',
    LOGIN_FIRST: 'Login first to check comments',
    LIKE: 'Like',
    UNLIKE: 'Unlike',
    LIKES: 'Like(s)',
}

export default CONSTANTS