const CONSTANTS = {
    SOMETHING_WENT_WRONG: 'Something went wrong',
    UPDATED: 'Updated',
    DELETED: 'Deleted',
    COMMENTED: 'Commented',
    USER_ALREADY_EXISTS: 'User already exists',
    POSTED: 'Posted',
    ADD_ALL_FIELDS: 'Please add all fields',
    INVALID_USER_DATA: 'Invalid user data',
    INCORRECT_EMAIL_OR_PASSWORD: 'Incorrect email or password',
    ENTER_NAME: 'Please add a name',
    ENTER_EMAIL: 'Please enter email',
    ENTER_PASSWORD: 'Please enter password',
    NOT_AUTH_NO_TOKEN: 'Not authorized, no token',
    NOT_AUTHORIZED: 'Not Authorized',
    MINUS_PASSWORD: '-password',
    BEARER: 'Bearer',
    ENTER_TITLE: 'Please add title',
    ENTER_BODY: 'Please add body',
    ENTER_COMMENT: 'Please add comment',
    COMMENTS_SCHEMA: 'comments',
    POSTS_SCHEMA: 'posts',
    USERS_SCHEMA: 'users',
    CANT_GET_INDIVIDUAL_POST: 'Cant get single post',
    EDIT_FAILED: 'Edit Failed',
    DELETION_FAILED: 'Deletion Failed',
    PUBLISH_NEW_POST_FAILED: 'Cant publish new post',
    PUBLISH_NEW_COMMENT_FAILED: 'Cant publish new comment',
    LOGIN_FAILED: 'Login failed',
    SIGNUP_FAILED: 'Signup failed',
    PROFILE_DATA_FAILED: 'Profile data loading failed',
    POST_FETCH_FAILED: 'Cant fetch all posts',
    COMMENTS_FETCH_FAILED: 'Cant fetch all comments',
    DISLIKE: 'dislike',
    LIKE: 'like',
    LIKED: 'Liked',
    DISLIKED: 'Disliked',
    LIKE_DISLIKE_FAILED: 'Cant like or disliked'
}

module.exports = CONSTANTS